- name: Configuration postgresql.conf
  lineinfile:
    line: "{{ item.name }} = '{{ item.value }}'"
    state: "{{ item.state|default('present') }}"
    dest: "/etc/postgresql/{{version}}/main/postgresql.conf"
    insertafter: '# Add settings for extensions here'
  notify: restart postgres
  with_items: "{{ pg_settings }}"

- name: Configuration pg_hba
  lineinfile:
    line: "{{ item.value }}"
    state: "{{ item.state|default('present') }}"
    dest: "/etc/postgresql/{{ version }}/main/pg_hba.conf"
  notify: reload postgres
  with_items: "{{ pg_hba_settings }}"
