- name: Databases
  postgresql_db:
    name: "{{ item.name }}"
    encoding: "{{ item.encoding|default('UTF-8') }}"
    lc_collate: "{{ item.lc_collate|default('en_US.UTF-8') }}"
    lc_ctype: "{{ item.lc_ctype|default('en_US.UTF-8') }}"
    owner: "{{ item.owner|default('postgres') }}"
    template: 'template0'
  become: yes
  become_user: "postgres"
  with_items: "{{ pg_databases }}"

- name: Databases Extensions
  postgresql_ext:
    name: "{{ item.1 }}"
    db: "{{ item.0.name }}"
  become: yes
  become_user: "postgres"
  with_subelements: 
    - "{{ pg_databases }}"
    - extensions
    - flags:
      skip_missing: True
