- include: install.yml
  tags:
    - postgresql-install

- include: configure.yml
  tags:
    - postgresql-configure

- meta: flush_handlers

- include: user.yml
  tags:
    - postgresql-user
  when: pg_users

- include: database.yml
  tags:
    - postgresql-database
  when: pg_databases
