- name: Users
  postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.pass|default(item.name) }}"
    role_attr_flags: "{{ item.role_attr_flags|default('LOGIN') }}"
  become: yes
  become_user: "postgres"
  with_items: "{{ pg_users }}"
